"""set history

Revision ID: 02f440bf4dbe
Revises: 16b3b5a2acb5
Create Date: 2022-08-24 15:33:15.936730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f440bf4dbe'
down_revision = '16b3b5a2acb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'history', ['id'])
    op.create_foreign_key(None, 'history', 'auth', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'history', 'auth', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_constraint(None, 'history', type_='unique')
    # ### end Alembic commands ###
