"""set3 history

Revision ID: 0ceecebd0eaf
Revises: f800e3df6a73
Create Date: 2022-08-24 15:44:32.995909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ceecebd0eaf'
down_revision = 'f800e3df6a73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('commission', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'commission')
    op.drop_column('history', 'price')
    # ### end Alembic commands ###
