"""set history

Revision ID: 111bd75e7fd8
Revises: 02f440bf4dbe
Create Date: 2022-08-24 15:42:32.504883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111bd75e7fd8'
down_revision = '02f440bf4dbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
