"""create history table

Revision ID: 16b3b5a2acb5
Revises: 524a6eb99c7a
Create Date: 2022-08-24 15:25:28.037482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b3b5a2acb5'
down_revision = '524a6eb99c7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('commission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'auth', ['id'])
    op.create_unique_constraint(None, 'change', ['id'])
    op.create_unique_constraint(None, 'news_product', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_product', type_='unique')
    op.drop_constraint(None, 'change', type_='unique')
    op.drop_constraint(None, 'auth', type_='unique')
    op.drop_table('history')
    # ### end Alembic commands ###
