"""set2 history

Revision ID: f800e3df6a73
Revises: 111bd75e7fd8
Create Date: 2022-08-24 15:44:09.640742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f800e3df6a73'
down_revision = '111bd75e7fd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'price')
    op.drop_column('history', 'commission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('commission', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('history', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
